name    'alkivi-phpmyadmin'
version '0.0.1'
source 'https://github.com/alkivi/puppet-phpmyadmin'
author 'alkivi'
license 'LGPLv3'
summary 'Controls basic installation of phpmyadmin'
description 'Setup phpmyadmin package, and just that, no web server conf nothing else'
project_page 'https://github.com/alkivi/puppet-phpmyadmin'
dependency 'puppetlabs/stdlib', '>3.x'
dependency 'puppetlabs/concat', '1.0.0'
dependency 'puppetlabs/apache', '>0.x'
dependency 'alkivi/alkivi_base', '>0.x'
dependency 'alkivi/mysql', '>0.x'
